theme: jekyll-theme-minimal

title: Sergio Junior
logo: /images/photo.jpg
email: sergio.junior55@hotmail.com

lang: en_US
curriculum: SergioJunior_CV_English
localization: Belo Horizonte, MG, Brazil

google_analytics: G-L5DKNEFTBC
